/** Statik ülke listesi — müşteri formu açılır listesi (backend ile aynı) */
export const COUNTRIES = [
  'Türkiye',
  'Almanya',
  'Amerika Birleşik Devletleri',
  'Fransa',
  'İngiltere',
  'İtalya',
  'İspanya',
  'Hollanda',
  'Belçika',
  'Avusturya',
  'İsviçre',
  'Polonya',
  'Romanya',
  'Bulgaristan',
  'Yunanistan',
  'Rusya',
  'Çin',
  'Japonya',
  'Güney Kore',
  'Hindistan',
  'Birleşik Arap Emirlikleri',
  'Suudi Arabistan',
  'Katar',
  'Mısır',
  'Azerbaycan',
  'Kazakistan',
  'Özbekistan',
  'Gürcistan',
  'Ukrayna',
  'Kanada',
  'Brezilya',
  'Meksika',
  'Avustralya',
  'Güney Afrika',
  'İsveç',
  'Norveç',
  'Danimarka',
  'Finlandiya',
  'Portekiz',
  'Çekya',
  'Macaristan',
  'Slovakya',
  'Sırbistan',
  'Hırvatistan',
  'İrlanda',
  'Singapur',
  'Malezya',
  'Endonezya',
  'Tayland',
  'Vietnam',
  'İsrail',
  'İran',
  'Irak',
  'Suriye',
  'Lübnan',
  'Ürdün',
  'Fas',
  'Tunus',
  'Cezayir',
  'Nijerya',
  'Kenya',
  'Arjantin',
  'Şili',
  'Kolombiya',
  'Peru',
  'Yeni Zelanda',
  'Diğer',
] as const
