/** Statik ülke listesi — müşteri formu açılır listesi (backend / mobil ile aynı) */
export const COUNTRIES = [
  'Türkiye',
  'Afganistan',
  'Almanya',
  'Amerika Birleşik Devletleri',
  'Andorra',
  'Angola',
  'Antigua ve Barbuda',
  'Arjantin',
  'Arnavutluk',
  'Avustralya',
  'Avusturya',
  'Azerbaycan',
  'Bahamalar',
  'Bahreyn',
  'Bangladeş',
  'Barbados',
  'Belarus',
  'Belçika',
  'Belize',
  'Benin',
  'Birleşik Arap Emirlikleri',
  'Bolivya',
  'Bosna-Hersek',
  'Botsvana',
  'Brezilya',
  'Brunei',
  'Bulgaristan',
  'Burkina Faso',
  'Burundi',
  'Butan',
  'Cezayir',
  'Cibuti',
  'Çad',
  'Çekya',
  'Çeçenistan',
  'Çin',
  'Danimarka',
  'Demokratik Kongo Cumhuriyeti',
  'Doğu Timor',
  'Dominika',
  'Dominik Cumhuriyeti',
  'Ekvador',
  'Ekvator Ginesi',
  'El Salvador',
  'Endonezya',
  'Eritre',
  'Ermenistan',
  'Estonya',
  'Esvatini',
  'Etiyopya',
  'Fas',
  'Fiji',
  'Fildişi Sahili',
  'Filipinler',
  'Filistin',
  'Finlandiya',
  'Fransa',
  'Gabon',
  'Gambiya',
  'Gana',
  'Gine',
  'Gine-Bissau',
  'Grenada',
  'Guyana',
  'Guatemala',
  'Güney Afrika',
  'Güney Kore',
  'Güney Sudan',
  'Gürcistan',
  'Haiti',
  'Hırvatistan',
  'Hindistan',
  'Hollanda',
  'Honduras',
  'Irak',
  'İngiltere',
  'İran',
  'İrlanda',
  'İspanya',
  'İsrail',
  'İsveç',
  'İsviçre',
  'İtalya',
  'İzlanda',
  'Jamaika',
  'Japonya',
  'Kamboçya',
  'Kamerun',
  'Kanada',
  'Karadağ',
  'Katar',
  'Kazakistan',
  'Kenya',
  'Kırgızistan',
  'Kıbrıs',
  'Kiribati',
  'Kolombiya',
  'Komorlar',
  'Kongo Cumhuriyeti',
  'Kosova',
  'Kosta Rika',
  'Küba',
  'Kuveyt',
  'Kuzey Kıbrıs',
  'Kuzey Kore',
  'Kuzey Makedonya',
  'Laos',
  'Lesotho',
  'Letonya',
  'Liberya',
  'Libya',
  'Lihtenştayn',
  'Litvanya',
  'Lübnan',
  'Lüksemburg',
  'Macaristan',
  'Madagaskar',
  'Malavi',
  'Maldivler',
  'Malezya',
  'Mali',
  'Malta',
  'Marshall Adaları',
  'Mauritius',
  'Meksika',
  'Mısır',
  'Mikronezya',
  'Moğolistan',
  'Moldova',
  'Monako',
  'Moritanya',
  'Mozambik',
  'Myanmar',
  'Namibya',
  'Nauru',
  'Nepal',
  'Nijer',
  'Nijerya',
  'Nikaragua',
  'Norveç',
  'Orta Afrika Cumhuriyeti',
  'Özbekistan',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua Yeni Gine',
  'Paraguay',
  'Peru',
  'Polonya',
  'Portekiz',
  'Romanya',
  'Ruanda',
  'Rusya',
  'Saint Kitts ve Nevis',
  'Saint Lucia',
  'Saint Vincent ve Grenadinler',
  'Samoa',
  'San Marino',
  'Sao Tome ve Principe',
  'Senegal',
  'Seyşeller',
  'Sierra Leone',
  'Singapur',
  'Sırbistan',
  'Slovakya',
  'Slovenya',
  'Solomon Adaları',
  'Somali',
  'Sri Lanka',
  'Sudan',
  'Surinam',
  'Suriye',
  'Suudi Arabistan',
  'Şili',
  'Tacikistan',
  'Tanzanya',
  'Tayland',
  'Tayvan',
  'Togo',
  'Tonga',
  'Trinidad ve Tobago',
  'Tunus',
  'Tuvalu',
  'Türkmenistan',
  'Uganda',
  'Ukrayna',
  'Umman',
  'Uruguay',
  'Ürdün',
  'Vanuatu',
  'Vatikan',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Yeni Zelanda',
  'Yeşil Burun Adaları',
  'Yunanistan',
  'Zambiya',
  'Zimbabve',
  'Diğer',
] as const
